apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: git-credentials
spec:
  encryptedData:
    password: AgCGhqDfMIuuXmeeaPVOm7qsNgLsUMkWkji5Wq1WvKJ1vyQML0esWh3GIoLDYrIMBAIF14Tu6k2+v+NeoCkZe8sc6jQl94VyDY6oewoGmHIU91ac0gPlhNObLTKrvYYbTWggvpf+1hJlmFQjC5PX63Mxpm4xvX5y3nFBQuGB9P0QJFEyQha9ez8n15JVpbgt8Rv8MybzV+0OMFVkaRA1b3FR5na4/iI7MvrdSQioOk4n2GsPJKHx9jUqQ6WFWKCkTLcmR9FW0Ca+cXh9FJLpoKaXEiuuvyrTR+pjgvtpeynWpzXROhkApLARSfiy/2NRjK/JVyv7WhOksP8xBYwLcanRIqIDI1yHBpUVMuIxZz7npIfiEPDLhM538rGS6a5mViKjCL+/Ol4AUMGNkzrrRs+9qNuscOhkcZCluWmE+HIuvn6/op096dD3VlJeHidAty7iz2VSgqnF80IUHRiOxEfzHFebJociPBH46ynVJZwVmQk75OxlFi50OPzwRmAm3ooNqM1KbIo5w2fMOeGkyjDbJvUFI86Mmxnsi7BjHPohqxKNE8doA4rm6XiN4Mj4BnbXe4n4CsZ3ctU6Mm4zqvdIck9Cz9rWMClMYesJ77PpcS4fAeWQ68Y6y2LFAIU8fzSzNP2nkQRvTRXfju7lOce9VHyEz6R1YXdBv+J+bov1cpNVWPImBkhjG6cc4kqw+FNdzxLLUuRtPsgLHL6HxTWuSrGr7QWQiJQn46zKfWhkIrgHP9jLnVVH
    username: AgCkxtxup7J3udsQH1pPreaI/pJnbR4nb7pVBMD2YpOVM+qWppERRP1CCegwgwpVN9womZY9I7MKCP3WAm7Rj8PPKz8KELbldDpoY03mdWH6OOba1rmHdFh49x1aYE99Q1luD+ydmrZ+YWjHu267pz5G4LSaonV8Hpf9lIick/dGbFg4Br/ak/QiA4Pk3Wx3DXiYiD3SAYf4ypg12YN/Smcqmir6PDTdrc3XTn0rF4+wJooup8zCatVVy0OqHXO1G5hVxikRLNetTjWjzU7i8UGp5j2nLX0Za3MBcT9ynnipoU/YXnGH8bAFHTtRsdcJpRwkUoNYPFcJQ6kaq/+zurnh838SnrlVGX1WYL+17eeK18QSpyTmM/10Tz9YN9Gdb8rbVZ0yofoIulRe7fhJeHL1deZRjGxnSgLaV6dbtorm0u98Ae9Ucr5G99zsNyKiLY0Jk4umTOqPEj3sLR1ORD39Qj2EBU3TqUFBj4mYX7hRqX73VcCRMhRNkuMgbQd479MyrdGhz4VcpizFykwFPx8Y6/TlwFt4qu3HDhbaBd/rTmc4O2wV7v3FMSzyDRTiSKn/P0aFNCzhUZchBCjli+Xcsbj4lt0whbRzPWbZu6VsR08Z0YW3H2UKZNBGDv3Xd9eqI3Wx0AgPDWs9wb8ZomTs1sdB777HP8HaKzYaRxXTDo9PTeIxhdqGYrhRJRB+wPzGQKMIIus=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
        tekton.dev/git-0: https://github.com
      creationTimestamp: null
      name: git-credentials
    type: kubernetes.io/basic-auth

